---
name: Website
on:
  push:
    branches:
      - master
      - "release/**"
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'website/docs/**'
      - '.github/workflows/**'

env:
  GO_VERSION: "1.15"
  GOPROXY: https://gocenter.io,https://proxy.golang.org,direct

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        name: markdown-link-check website/docs/**/*.markdown
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdownlinkcheck.json'
          folder-path: 'website/docs'
          file-extension: '.markdown'
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        name: markdown-link-check website/docs/**/*.md
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdownlinkcheck.json'
          folder-path: 'website/docs'
          file-extension: '.md'


