---
name: Website
on:
  push:
    branches:
      - master
      - "release/**"
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'website/**'
      - '.github/workflows/**'

env:
  GO_VERSION: "1.15"
  GOPROXY: https://gocenter.io,https://proxy.golang.org,direct

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: bash scripts/gogetcookie.sh
      - run: |
          cat /etc/issue
          echo "whoami" && whoami
          sudo mkdir -p /go && sudo chown -R $(whoami) /go
          export GOPATH="/go"
          echo "GOPATH: $GOPATH"
          make website-test


